import React, {useEffect,useState,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {AnimatePresence,MotionConfig,motion,useReducedMotion} from 'framer-motion';
import {gsap} from 'gsap';
import {ScrollTrigger} from 'gsap/ScrollTrigger';
import {ScrollToPlugin} from 'gsap/ScrollToPlugin';
import {useGSAP} from '@gsap/react';
import './app.css';
import EvidenceReader,{readerURL,sourceTitle} from './EvidenceReader.jsx';
gsap.registerPlugin(ScrollTrigger,ScrollToPlugin,useGSAP);

const PUBLIC_PREVIEW=__PUBLIC_PREVIEW__;
const Arrow=()=> <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" aria-hidden="true"><path d="M4 12h16m-6-6 6 6-6 6"/></svg>;
const evidence=p=>'/evidence/'+p.split('/').map(encodeURIComponent).join('/');
const metric=m=>typeof m.value==='number'?(m.format==='percent'?(100*m.value).toFixed(1)+'%':m.format==='integer'?m.value.toLocaleString():m.value.toFixed(3)):String(m.value);
async function request(url,options){if(PUBLIC_PREVIEW){const metadata={'/model-info':'model','/api/journey':'journey','/api/examples':'examples','/api/purpose':'purpose','/api/evidence-index':'evidence_index'};if(metadata[url])url='/metadata/'+metadata[url]+'.json';else if(url==='/api/inspect-example'){url='/benchmarks/'+encodeURIComponent(JSON.parse(options.body).id)+'.json';options=undefined;}else if(url==='/api/inspect')throw new Error('Live uploads are available in the local Python application.');}const r=await fetch(url,options);const data=await r.json();if(!r.ok)throw new Error(data.error||'This request could not be completed.');return data;}
function Link({to,children,...props}){return <a href={to} {...props} onClick={e=>{if(e.button===0&&!e.ctrlKey&&!e.metaKey&&!e.shiftKey&&!e.altKey){e.preventDefault();history.pushState({},'',to);window.dispatchEvent(new PopStateEvent('popstate'));}}}>{children}</a>;}
function ProfileLinks({label}){return <nav className="profile-links" aria-label={label}><a href="https://www.linkedin.com/in/pantavis-tantivongsakij-3176212b2/" target="_blank" rel="noreferrer">LinkedIn <Arrow/></a><a href="https://github.com/beam-9" target="_blank" rel="noreferrer">GitHub <Arrow/></a><a href="https://github.com/beam-9/pcb-inspection" target="_blank" rel="noreferrer">Project source <Arrow/></a></nav>;}
function AuthorIntro(){return <section className="author-intro" aria-labelledby="author-heading"><div><p className="author-label">About the builder</p><h2 id="author-heading">Pantavis Tantivongsakij</h2></div><div><p>I'm a Data Science student at the University of British Columbia. I built this project to explore how visual anomaly detection can support PCB inspection, and to make the experiments and remaining failures easy to review.</p><ProfileLinks label="About author profiles"/></div></section>;}
function Sources({stage}){return <ul className="sources">{stage.sources.map(s=><li key={s.path}><Link to={readerURL(s.path)}>{sourceTitle(s)}<Arrow/></Link></li>)}</ul>;}
function Home({data}){const ex=data.examples.examples.find(e=>e.id==='reversed_anomaly');const stats=data.model.metrics.image;return <>
 <div className="home-title"><h1>Inspect a PCB.<br/><em>See how the model works.</em></h1><div><p>Compare a board with normal reference patches, then follow the experiments behind the selected detector.</p><Link to="/inspect" className="button">{PUBLIC_PREVIEW?'Explore saved inspections':'Inspect a board'} <Arrow/></Link></div></div>
 <motion.section className="workbench hero-bench" aria-label="Saved benchmark preview" initial={{opacity:1,y:12}} animate={{opacity:1,y:0}} transition={{duration:.45}}>
  <div className="plate"><div className="pair"><figure><figcaption>Original · PCB2</figcaption><img src={ex.thumbnail} alt="Real reversed PCB2 benchmark board"/></figure><figure><figcaption>Anomaly response</figcaption><img src={ex.saved_heatmap} alt="Saved source-space response for the same board"/></figure></div><div className="plate-caption"><span>Reversed benchmark · saved Stage 5C result</span><span>Fixed response scale · not probability</span></div></div>
  <aside className="measurement"><h2>Just above <br/>the threshold.</h2><p>Correcting this board’s 180° orientation raises its anomaly score just above the frozen threshold.</p><dl><div><dt>Image score</dt><dd>{ex.saved_score.toFixed(4)}</dd></div><div><dt>Frozen threshold</dt><dd>{data.model.thresholds.image_threshold.toFixed(4)}</dd></div><div><dt>Orientation</dt><dd>180° reversed</dd></div></dl><Link to="/inspect?example=reversed_anomaly" className="text-link">Inspect this example <Arrow/></Link><small>{PUBLIC_PREVIEW?'Real benchmark and recorded v1.0 response. Public previews do not run a new inspection.':'The image is a real benchmark. The preview is saved evidence; inspection runs the model again.'}</small></aside>
 </motion.section>
 <section className="home-evidence"><div><h2>How I reached<br/><em>this model.</em></h2><p>I built a reference from normal patches without training on defect classes. After investigating the remaining misses, I froze the selected recipe.</p><Link to="/journey" className="text-link">Follow the experiments <Arrow/></Link></div><div><p className="scope">PCB2 post-confirmation development · 200 images</p><dl className="stat-line"><div><dt>Anomaly recall</dt><dd>{(stats.recall*100).toFixed(0)}%</dd></div><div><dt>Normal false alarms</dt><dd>{(stats.normal_false_alarm_rate*100).toFixed(0)}%</dd></div><div><dt>Missed anomalies</dt><dd>{stats.fn} / {stats.anomaly_count}</dd></div></dl><p className="muted">PCB2 had already guided development when these results were measured. They are not a fresh independent test. The detector still misses some small and missing defects.</p><Link to="/model" className="text-link">Read the model card <Arrow/></Link></div></section><Purpose data={data} compact/>
 </>;}
function App(){const [path,setPath]=useState(location.pathname);const [data,setData]=useState(null);const [error,setError]=useState('');const reduced=useReducedMotion();async function load(){setError('');try{const [model,journey,examples,purpose,evidenceIndex]=await Promise.all(['/model-info','/api/journey','/api/examples','/api/purpose','/api/evidence-index'].map(u=>request(u)));setData({model,journey,examples,purpose,evidenceIndex});}catch(e){setError(e.message);}}
 useEffect(()=>{load();const change=()=>{setPath(location.pathname);if(!location.hash)window.scrollTo(0,0);};window.addEventListener('popstate',change);return()=>window.removeEventListener('popstate',change);},[]);
 useEffect(()=>{if(!data||!location.hash)return;const timer=setTimeout(()=>document.getElementById(location.hash.slice(1))?.scrollIntoView(),220);return()=>clearTimeout(timer);},[path,data]);
 useEffect(()=>{document.title=(path==='/inspect'?'Inspect':path.startsWith('/journey')?'Engineering journey':path==='/model'?'Model card':path==='/about'?'About':path.startsWith('/read/')?'Project source':'Inspection & engineering journey')+' · PCB-AD';},[path]);
 return <><a className="skip" href="#main">Skip to content</a><header className="header"><Link to="/" className="wordmark">PCB–AD<span>v1.0</span></Link><nav aria-label="Main navigation">{[['/inspect','Inspect'],['/journey','Journey'],['/model','Model'],['/about','About']].map(([to,label])=><Link key={to} to={to} aria-current={path.startsWith(to)?'page':undefined}>{label}</Link>)}</nav><span className="local-label"><i/>{PUBLIC_PREVIEW?'Saved evidence preview':'Local research demo'}</span></header>
 <main id="main" tabIndex="-1">{error?<div className="service-error" role="alert"><h1>{PUBLIC_PREVIEW?'The evidence could not be loaded.':'The local service needs attention.'}</h1><p>{error}</p><button className="button" onClick={load}>Retry connection</button></div>:!data?<p className="loading" role="status">Loading the model and project records…</p>:<AnimatePresence mode="wait"><motion.div key={path} initial={{opacity:1,x:reduced?0:8}} animate={{opacity:1,x:0}} exit={{opacity:0}} transition={{duration:reduced?0:.16}}>{path==='/'?<Home data={data}/>:<Page path={path} data={data}/>}</motion.div></AnimatePresence>}</main>
 <footer><div className="footer-top"><div className="footer-identity"><Link to="/">PCB–AD v1.0</Link><p>Built by Pantavis Tantivongsakij</p></div><ProfileLinks label="Footer author profiles"/></div><div className="footer-bottom"><p>Research demo. A low score can still miss a defect.</p><a href="https://github.com/amazon-science/spot-diff" target="_blank" rel="noreferrer">VisA imagery · Amazon Science</a></div></footer></>;}
function ImageSurface({result,view,opacity,threshold,gt}){const canvas=useRef(null);useEffect(()=>{const c=canvas.current;if(!c||(!threshold&&!gt))return;const ctx=c.getContext('2d');let active=true;ctx.clearRect(0,0,c.width,c.height);async function mask(url,color){const im=new Image();im.src=url;await im.decode();if(!active)return;const temp=document.createElement('canvas');temp.width=c.width;temp.height=c.height;const t=temp.getContext('2d');t.drawImage(im,0,0,temp.width,temp.height);const pixels=t.getImageData(0,0,temp.width,temp.height);for(let i=0;i<pixels.data.length;i+=4){const on=pixels.data[i]>0;pixels.data[i]=color[0];pixels.data[i+1]=color[1];pixels.data[i+2]=color[2];pixels.data[i+3]=on?color[3]:0;}t.putImageData(pixels,0,0);ctx.drawImage(temp,0,0);}
 (async()=>{if(threshold)await mask(result.thresholded_map,[255,218,88,130]);if(gt&&result.ground_truth)await mask(result.ground_truth,[53,231,222,175]);})();return()=>{active=false;};},[result,threshold,gt]);return <div className="image-surface" style={{aspectRatio:result.display_size.join('/')}}><img src={view==='Heatmap'?result.heatmap:result.original} alt={view==='Heatmap'?'Anomaly response in original image coordinates':'Original inspected board'}/>{view==='Overlay'&&<img src={result.heatmap} alt="" className="overlay" style={{opacity:opacity/100}}/>}{(threshold||gt)&&<canvas ref={canvas} width={result.display_size[0]} height={result.display_size[1]} aria-label={gt?'Cyan benchmark annotation; yellow thresholded response if enabled':'Yellow response above the frozen pixel threshold'}/>}</div>;}
function Inspect({data}){const selectedQuery=new URLSearchParams(location.search).get('example');const initial=data.examples.examples.find(e=>e.id===selectedQuery)||data.examples.examples[1];const [sample,setSample]=useState(initial);const [file,setFile]=useState(null);const [preview,setPreview]=useState('');const [result,setResult]=useState(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [view,setView]=useState('Overlay');const [opacity,setOpacity]=useState(45);const [threshold,setThreshold]=useState(false);const [gt,setGt]=useState(false);const [drag,setDrag]=useState(false);const input=useRef(null);const status=useRef(null);const reduced=useReducedMotion();
 useEffect(()=>{if(!file){setPreview('');return;}const url=URL.createObjectURL(file);setPreview(url);return()=>URL.revokeObjectURL(url);},[file]);
 function choose(f){if(PUBLIC_PREVIEW||busy||!f)return;setError('');setResult(null);if(f.size>12*1024*1024){setError('This image exceeds 12 MiB. Choose a smaller JPEG, PNG or WebP.');return;}if(!['image/jpeg','image/png','image/webp'].includes(f.type)){setError('Choose a JPEG, PNG or WebP still image.');return;}setFile(f);setSample(null);setGt(false);}
 async function run(){if(busy)return;setBusy(true);setError('');setResult(null);setGt(false);try{const r=file?await request('/api/inspect',{method:'POST',headers:{'Content-Type':file.type},body:file}):await request('/api/inspect-example',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:sample.id})});setResult(r);setTimeout(()=>status.current?.focus(),0);}catch(e){setError(e.message+' Choose another image or try again.');}finally{setBusy(false);}}
 return <><div className="page-heading"><h1>Inspection workbench.</h1><p>Compare a board with the model’s fixed set of normal reference patches.<br/>{PUBLIC_PREVIEW?'Explore recorded benchmark results.':'Choose a benchmark or upload an image.'}</p></div>{PUBLIC_PREVIEW&&<p className="preview-notice">This preview displays saved model results. To inspect an uploaded image, run the local Python app.</p>}
 <div className="inspect-input"><div className={'dropzone '+(drag?'dragging':'')} onDragOver={e=>{e.preventDefault();setDrag(true);}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);choose(e.dataTransfer.files[0]);}}><button className="upload-button" disabled={PUBLIC_PREVIEW||busy} onClick={()=>input.current.click()}><svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" aria-hidden="true"><path d="M12 16V3m-5 5 5-5 5 5M4 15v6h16v-6"/></svg><span>{PUBLIC_PREVIEW?'Live uploads run in the local app':file?file.name:'Choose an image or drop it here'}<small>{PUBLIC_PREVIEW?'Choose a benchmark to view its saved result.':'JPEG, PNG or WebP · up to 12 MiB · stays in memory'}</small></span></button><input ref={input} tabIndex="-1" aria-label="Upload board image" type="file" accept="image/jpeg,image/png,image/webp" disabled={PUBLIC_PREVIEW||busy} onChange={e=>choose(e.target.files[0])}/></div><div className="sample-select"><label htmlFor="example">Choose a PCB2 benchmark</label><select id="example" value={sample?.id||''} disabled={busy} onChange={e=>{const ex=data.examples.examples.find(x=>x.id===e.target.value);setSample(ex);setFile(null);setResult(null);setError('');setGt(false);if(input.current)input.current.value='';}}>{!sample&&<option value="" disabled>Uploaded image selected</option>}{data.examples.examples.map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select></div><button onClick={run} disabled={busy||(!file&&!sample)} className="button">{busy?(PUBLIC_PREVIEW?'Loading saved result…':'Running inspection…'):(PUBLIC_PREVIEW?'View saved result':'Run inspection')}{!busy&&<Arrow/>}</button></div>
 {error&&<p className="error" role="alert">{error}</p>}
 <div className="workbench inspect-bench"><section className="plate" aria-label="Inspection image"><div className="view-controls">{['Original','Overlay','Heatmap'].map(v=><button key={v} aria-pressed={view===v} disabled={!result} onClick={()=>setView(v)}>{view===v&&<motion.span className="view-highlight" layoutId="image-view" transition={{type:'spring',stiffness:400,damping:35}}/>}<span>{v}</span></button>)}<span className="plate-version">{data.model.name}</span></div>
  <AnimatePresence mode="wait">{result?<motion.div key="result" initial={{opacity:0}} animate={{opacity:1}} transition={{duration:reduced?0:.25}}><ImageSurface result={result} view={view} opacity={opacity} threshold={threshold} gt={gt}/></motion.div>:<motion.div key="preview" className="inspection-preview"><img src={preview||sample?.thumbnail} alt={file?'Selected upload preview':'Selected real PCB2 benchmark preview'}/>{busy&&<div className="processing" role="status">{PUBLIC_PREVIEW?'Loading recorded evidence…':'Running the frozen detector…'}</div>}</motion.div>}</AnimatePresence>
  {result?<><div className="overlay-controls"><label htmlFor="opacity">Overlay opacity <output>{opacity}%</output></label><input id="opacity" type="range" min="0" max="100" value={opacity} disabled={view!=='Overlay'} onChange={e=>setOpacity(Number(e.target.value))}/><label className="checkbox"><input type="checkbox" checked={threshold} onChange={e=>setThreshold(e.target.checked)}/>Yellow: response above pixel threshold</label>{result.ground_truth&&<label className="checkbox"><input type="checkbox" checked={gt} onChange={e=>setGt(e.target.checked)}/>Cyan: benchmark union annotation</label>}</div><div className="scale"><div className="color-scale"/><div><span>0</span><span>1 · pixel threshold</span><span>2+</span></div></div><p className="plate-note">Colours show response divided by the fixed pixel threshold, on a scale from 0 to 2+. They do not show defect probability or exact boundaries.</p></>:<p className="plate-note">{sample?.description||'Uploaded images have no ground-truth annotation.'} {PUBLIC_PREVIEW?'View the saved result to explore its recorded response.':'Run inspection to compute the response.'}</p>}
 </section><aside className="measurement result-rail"><AnimatePresence mode="wait">{result?<motion.div key="decision" initial={{opacity:0,y:reduced?0:8}} animate={{opacity:1,y:0}}><div ref={status} tabIndex="-1" role="status" className={'decision '+(result.is_anomalous?'flag':'no-flag')}><h2>{result.is_anomalous?'Anomaly flagged.':'No anomaly flagged.'}</h2><p>{result.is_anomalous?'The image score is above the fixed threshold. Check the response against the original board.':'The score is below the threshold. The board may still contain a defect.'}</p></div><dl><div><dt>Image score</dt><dd>{result.anomaly_score.toFixed(4)}</dd></div><div><dt>Image threshold</dt><dd>{result.image_threshold.toFixed(4)}</dd></div><div><dt>Pose</dt><dd>{result.pose_label.replace('_180',' 180°')}</dd></div><div><dt>180° normalization</dt><dd>{result.normalization_applied?'Applied':'Not applied'}</dd></div><div><dt>Crop fallback</dt><dd>{result.crop_fallback?'Yes':'No'}</dd></div><div><dt>{PUBLIC_PREVIEW?'Recorded inference runtime':'Inference runtime'}</dt><dd>{result.runtime.end_to_end_seconds.toFixed(2)} s</dd></div></dl>{result.pose_label==='uncertain'&&<p className="notice">The orientation cue is uncertain, so the crop stays unchanged. {result.pose_uncertainty_reason}</p>}{result.benchmark?.id==='known_small_missing_miss'&&<p className="notice">The model misses a missing-label defect in this example. I kept the result so you can inspect that failure.</p>}<details><summary>Exact values & processing</summary><dl className="exact"><div><dt>Image score</dt><dd>{result.anomaly_score}</dd></div><div><dt>Image threshold</dt><dd>{result.image_threshold}</dd></div><div><dt>Pixel threshold</dt><dd>{result.pixel_threshold}</dd></div><div><dt>Comparison</dt><dd>Strict &gt;</dd></div><div><dt>Original size</dt><dd>{result.source_size.join(' × ')}</dd></div><div><dt>Crop box</dt><dd>{result.crop_box?.join(', ')}</dd></div></dl><p>Runtime covers preprocessing, feature scoring and inverse mapping; it excludes browser transfer and rendering.</p></details></motion.div>:<div><h2>{busy?'Inspection in progress.':'Choose an image to begin.'}</h2><p>{busy?(PUBLIC_PREVIEW?'Loading a recorded frozen-model result.':'Real CPU inference is running against the frozen memory bank.'):(PUBLIC_PREVIEW?'Choose a benchmark and view its recorded score, decision and orientation.':'Select an image and run inspection. The score, decision and orientation will appear here.')}</p><dl><div><dt>Input</dt><dd>{data.model.input_size} × {data.model.input_size}</dd></div><div><dt>Normal patch references</dt><dd>{data.model.memory_size.toLocaleString()}</dd></div><div><dt>Frozen image threshold</dt><dd>{data.model.thresholds.image_threshold.toFixed(4)}</dd></div></dl></div>}</AnimatePresence><Link to="/model" className="text-link">Model & limitations <Arrow/></Link><small>PCB2-specific research demo. Arbitrary boards, rotations and capture conditions are outside demonstrated coverage.</small></aside></div>
 <div className="inspection-footnote"><h3>Try a case the model misses.</h3><p>The examples include a normal board and detected defects, as well as a reversed board, an uncertain pose and a known miss. You can view the benchmark annotations after inspection. The detector never uses them.</p></div></>;
}
function JourneyScroll({stages,children}){
 const scope=useRef(null);const bar=useRef(null);const fill=useRef(null);const [active,setActive]=useState(0);const reduced=useReducedMotion();
 const {contextSafe}=useGSAP(()=>{
  const root=scope.current;const rows=[...root.querySelectorAll('.journey-row')];const media=gsap.matchMedia();let alive=true;let frame;
  media.add({reduce:'(prefers-reduced-motion: reduce)',motion:'(prefers-reduced-motion: no-preference)'},context=>{
   gsap.fromTo(fill.current,{scaleX:0},{scaleX:1,ease:'none',scrollTrigger:{trigger:root,start:'top 20%',end:'bottom bottom',scrub:context.conditions.reduce?true:.2,invalidateOnRefresh:true}});
   rows.forEach((row,i)=>ScrollTrigger.create({trigger:row,start:'top 35%',end:'bottom 35%',onEnter:()=>setActive(i),onEnterBack:()=>setActive(i),onLeaveBack:()=>setActive(Math.max(0,i-1))}));
  });
  const refresh=()=>{if(!alive)return;cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{if(alive)ScrollTrigger.refresh();});};
  const images=[...root.querySelectorAll('img')];images.forEach(im=>im.addEventListener('load',refresh));document.fonts.ready.then(refresh);refresh();
  return()=>{alive=false;cancelAnimationFrame(frame);images.forEach(im=>im.removeEventListener('load',refresh));media.revert();};
 },{scope,dependencies:[stages],revertOnUpdate:true});
 const jump=contextSafe(i=>{const row=scope.current.querySelectorAll('.journey-row')[i];gsap.to(window,{duration:reduced?0:.65,ease:'power2.inOut',scrollTo:{y:row,offsetY:bar.current.offsetHeight+24,autoKill:true},overwrite:'auto',onComplete:()=>row.querySelector('h3 a')?.focus({preventScroll:true})});});
 return <div ref={scope} className="journey-scroll"><div ref={bar} className="journey-wayfinding"><p><span>Reading</span><strong>{stages[active].title}</strong></p><nav aria-label="Jump to journey stage">{stages.map((s,i)=><button key={s.id} aria-label={'Jump to '+s.title} aria-current={i===active?'step':undefined} onClick={()=>jump(i)}>{s.id==='model-v1'?'v1.0':s.id.replace('stage-','').toUpperCase()}</button>)}</nav><div className="reading-track" aria-hidden="true"><span ref={fill}/></div></div>{children}</div>;
}
function Journey({data,stageId}){const stages=data.journey.stages;if(stageId){const index=stages.findIndex(s=>s.id===stageId);const stage=stages[index];if(!stage)return <h1>Stage not found.</h1>;const previous=stages[index-1];const next=stages[index+1];return <><Link to="/journey" className="text-link">← All stages</Link><div className="page-heading detail-heading"><h1>{stage.title}.</h1><p>{stage.datasetPhase}<br/>{stage.id.replace('stage-','Stage ').replace('model-v1','Model v1.0')}</p></div><div className="detail-grid"><article><section><h2>What I tested</h2><p>{stage.question}</p></section><section><h2>Previous result</h2><p>{previous?previous.learning:'A normal-reference detector was needed before any controlled improvement could be assessed.'}</p></section><section><h2>Why this step</h2><p>{stage.rationale}</p></section><section><h2>What changed</h2><p>{stage.change}</p><h3>Held constant</h3><p>{stage.heldConstant}</p></section><section><h2>Results</h2><dl className="stage-metrics">{stage.metrics.map(m=><div key={m.label}><dt>{m.label}</dt><dd>{metric(m)}</dd><Link to={readerURL(m.source.path)}>View source</Link></div>)}</dl><p>{stage.learning}</p></section><section><h2>Limits and decision</h2><p>{stage.limits}</p><p>{stage.id==='stage-6a'?'Keep D2 + orientation fixed. These misses do not support one clear next change that preserves the detector.':stage.id==='model-v1'?'Make the selected detector available for review. Any later model change needs a new version.':'Use this result to choose the next experiment.'}</p></section><section><h2>What follows</h2><p>{stage.nextQuestion}</p>{next&&<Link to={'/journey/'+next.id} className="text-link">{next.title}<Arrow/></Link>}</section><section><h2>Original evidence</h2><Sources stage={stage}/></section></article><aside className="figure-column">{stage.figures.map(f=><figure key={f.path}><a href={evidence(f.path)} target="_blank" rel="noreferrer"><img loading="lazy" src={evidence(f.path)} alt={f.alt}/></a><figcaption>{f.alt} · Original saved project figure. Open for full resolution.</figcaption></figure>)}</aside></div></>;}
return <><div className="page-heading"><h1>The experiments<br/><em>behind v1.0.</em></h1><p>See what I changed, why I changed it,<br/>and what each result led me to try next.</p></div><div className="journey-intro"><p>These stages use different evidence: PCB1 development, a fresh PCB2 confirmation, then further development on PCB2. Keep those boundaries in mind when comparing results.</p><Link to={readerURL('artifacts/model_v1/final_model_receipt.json')} className="text-link">Model freeze record <Arrow/></Link></div><JourneyScroll stages={stages}>{stages.map((s,i)=><React.Fragment key={s.id}>{(i===0||s.datasetPhase!==stages[i-1].datasetPhase)&&<div className={'phase-boundary '+(i===3?'fresh':'')}><h2>{s.datasetPhase}</h2><p>{i===3?'I apply the selected PCB1 procedure to fresh PCB2 data before making further changes.':i===4?'After this confirmation, PCB2 has influenced the project. Later changes use development evidence.':i===0?'The first category is used to develop and compare the detector.':'The chosen recipe is frozen for a local research demonstration.'}</p></div>}<section className="journey-row"><div className="stage-index">{s.id==='model-v1'?'v1.0':s.id.replace('stage-','').toUpperCase()}</div><div className="stage-copy"><h3><Link to={'/journey/'+s.id}>{s.title}</Link></h3><p className="stage-question">{s.question}</p><p>{s.learning}</p><p className="stage-rationale"><strong>Why this step.</strong> {s.rationale}</p><dl className="compact-metrics">{s.metrics.slice(0,3).map(m=><div key={m.label}><dt>{m.label}</dt><dd>{metric(m)}</dd></div>)}</dl><Link to={'/journey/'+s.id} className="text-link">Read the decision <Arrow/></Link></div><figure><Link to={'/journey/'+s.id}><img loading="lazy" src={evidence(s.figures[0].path)} alt={s.figures[0].alt}/></Link><figcaption>{s.figures[0].alt}</figcaption></figure></section></React.Fragment>)}</JourneyScroll></>;}
function Pipeline(){return <ol className="pipeline"><li><strong>RGB image</strong><span>Board crop + letterbox</span></li><li><strong>Pose cue</strong><span>180° reversal only when decisive</span></li><li><strong>Frozen features</strong><span>ResNet18 · layers 2 + 3</span></li><li><strong>Normal memory</strong><span>Nearest Euclidean distance</span></li><li><strong>Score & map</strong><span>Strict frozen thresholds</span></li></ol>;}
function Model({data}){const m=data.model;const stats=m.metrics.image;const localization=m.metrics.localization_common256;return <><div className="page-heading"><h1>The selected model.</h1><p>{m.name} · version {m.version}<br/>One-class anomaly detection for a research demonstration.</p></div><Pipeline/><div className="model-grid"><section><h2>Recipe & identity</h2><dl className="recipe-list">{[['Backbone',m.backbone],['Feature layers',m.feature_layers.join(' + ')],['Input resolution',m.input_size+' × '+m.input_size],['Ordered normal patch bank',m.memory_size.toLocaleString()+' × '+m.config.feature_dimensions+' dimensions'],['Distance',m.config.distance],['Image score',m.config.image_aggregation],['Image threshold',m.thresholds.image_threshold],['Pixel threshold',m.thresholds.pixel_threshold],['Comparison','Strict >'],['Pose','Canonical: unchanged · reversed: exact 180° · uncertain: unchanged'],['Recipe commit',m.recipe_commit],['Bank SHA-256',m.config.memory.sha256]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><Link to={readerURL('artifacts/model_v1/final_model_receipt.json')} className="text-link">View the model freeze record <Arrow/></Link></section><section><h2>Results and limits</h2><p className="scope">{m.metrics.scope}</p><table><caption>PCB2 final candidate · {stats.n_images} images ({stats.normal_count} normal, {stats.anomaly_count} anomalous)</caption><tbody>{[['Anomaly recall',(stats.recall*100).toFixed(1)+'%'],['Normal false alarm rate',(stats.normal_false_alarm_rate*100).toFixed(1)+'%'],['Image average precision',stats.average_precision.toFixed(4)],['Image AUROC',stats.auroc.toFixed(4)],['Pooled pixel AP · common 256',localization.pixel_average_precision.toFixed(4)],['Pixel IoU · common 256',localization.pixel_iou.toFixed(4)],['TP / FN / FP / TN',[stats.tp,stats.fn,stats.fp,stats.tn].join(' / ')]].map(([k,v])=><tr key={k}><th scope="row">{k}</th><td>{v}</td></tr>)}</tbody></table><a href={evidence('artifacts/model_v1/final_metrics.json')} className="text-link">All saved metrics & subgroups <Arrow/></a><Link to="/about#methods" className="text-link">Tools, methodology & reasons <Arrow/></Link><h3 className="spaced">Model limitations</h3><ul className="limitations">{m.limitations.map(l=><li key={l}>{l}</li>)}</ul></section></div><section className="closing"><h2>Why I stopped here.</h2><p>Stage 6A examined the remaining misses with the detector unchanged. Six of the nine were canonical missing-label cases; eight were small cases, with overlap. I found no clear next change that the diagnosis supported, so I kept D2 + orientation fixed.</p><Link to="/journey/stage-6a" className="text-link">Read the stopping rule <Arrow/></Link></section></>;}
function Methods({data}){const p=data.purpose;return <section className="methods-section" id="methods"><h2>How I built it.</h2><p className="methods-intro">I wrote a small implementation inspired by PatchCore. The steps below explain how it works and why I chose them. I did not reproduce the authors’ full implementation.</p><div className="method-steps">{p.methods.map(item=><article key={item.title}><h3>{item.title}</h3><p>{item.text}</p><p className="method-reason"><strong>Why.</strong> {item.reason}</p></article>)}</div><div className="tool-table-wrap"><table className="tool-table"><caption>Project tools and recorded versions</caption><thead><tr><th scope="col">Tool / role</th><th scope="col">What it does</th><th scope="col">Why it was used</th></tr></thead><tbody>{p.tools.map(t=><tr key={t.name}><th scope="row"><strong>{t.name}</strong><span>{t.category}</span><small>{t.versions}</small></th><td>{t.use}</td><td>{t.reason}</td></tr>)}</tbody></table></div><div className="methods-sources">{p.sources.map(source=><Link key={source.path} to={readerURL(source.path)}>{source.title} <Arrow/></Link>)}</div></section>;}
function Purpose({data,compact=false}){const p=data.purpose;return <section id={compact?undefined:'purpose'} className={'purpose-section '+(compact?'purpose-compact':'')}><div><h2>Why I built this</h2><p className="purpose-thesis">{p.title}</p><p>{p.purpose}</p>{compact&&<Link to="/about" className="text-link">Read about the purpose and next steps <Arrow/></Link>}</div><div><h3>{p.inspiration.title}</h3><p>{p.inspiration.text}</p><a className="text-link" href={p.inspiration.source_url} target="_blank" rel="noreferrer">{p.inspiration.source_title}<Arrow/></a><p className="muted">{p.inspiration.boundary}</p></div>{!compact&&<><div className="purpose-principles">{p.principles.map(item=><div key={item.title}><h3>{item.title}</h3><p>{item.text}</p></div>)}</div><div className="one-class-purpose"><h3>Why a normal-reference detector?</h3><p>{p.why_one_class}</p><Link to="/journey" className="text-link">Read why I took each step <Arrow/></Link></div></>}</section>;}
function Future({data}){return <section className="future-section" id="future"><h2>Experiments I would try next</h2><p className="future-intro">v1.0 stays fixed. These ideas would need new experiments and, in some cases, new data. Each has a question to test and a result I would look for.</p>{data.purpose.future.map(item=><article className="future-row" key={item.title}><div><h3>{item.title}</h3><p className="proposal-status">{item.status}</p></div><div><p><strong>Why.</strong> {item.reason}</p><p><strong>Next experiment.</strong> {item.experiment}</p><p><strong>How I would judge it.</strong> {item.success}</p></div></article>)}<Link to="/journey/stage-6a" className="text-link">Read the Stage 6A stopping decision <Arrow/></Link></section>;}
function About({data}){return <><div className="page-heading"><h1>Why this project?<br/><em>And how did I build it?</em></h1><p>An inspection experiment with a record of what worked and what still fails.</p></div><nav className="about-contents" aria-label="About sections"><a href="#purpose">Purpose & Athena inspiration</a><a href="#methods">Tools & methods</a><a href="#future">Future improvements</a></nav><AuthorIntro/><Purpose data={data}/><div className="about-grid"><article><h2>What is being compared?</h2><p>A frozen network extracts features from small image patches. I compare those features with a bank of patches from normal boards. The farther a patch is from its nearest reference, the stronger its response. The largest native patch score determines whether the image exceeds the threshold.</p><p>The PatchCore-inspired pipeline uses normal reference images without learning named defect classes. Its map points to regions worth checking. It cannot tell you the defect type or guarantee its boundaries.</p><h2>Why keep the experiment history?</h2><p>The first detector had weak recall and maps. I tested board geometry and memory selection, then tried a fresh category. That exposed an orientation problem. After correcting it, I investigated the remaining misses before choosing to stop.</p><p>The journey separates PCB1 development from fresh PCB2 confirmation and later PCB2 development. Each stage links to the original tables, figures and reports.</p><h2>What comes after v1.0?</h2><p>A later model needs a new version, a clear hypothesis and, where practical, an untouched evaluation category. I still need to study factory conditions, arbitrary rotation, small defects and physical board identity.</p><Link to="/journey" className="button">Read the experiment history <Arrow/></Link></article><aside><figure><img src="/assets/known_small_missing_miss.jpg" alt="Real small missing-label PCB2 anomaly missed by the frozen detector"/><figcaption>A missing-label anomaly the detector misses. You can try it in the inspection selector.</figcaption></figure><div className="about-note"><h3>A low score can miss a defect.</h3><p>This board contains a defect, but its score stays below the threshold.</p><Link to="/inspect?example=known_small_missing_miss" className="text-link">Inspect this missed defect <Arrow/></Link></div><p className="muted">The PCB examples come from Amazon Science’s VisA dataset. The local app keeps uploaded images in memory and does not save them.</p></aside></div><Methods data={data}/><Future data={data}/><p className="dataset-credit">VisA by Yang Zou, Jongheon Jeong, Latha Pemula, Dongqing Zhang and Onkar Dabeer. PCB photographs are resized for display; anomaly responses and annotated project figures are derivatives. <a href="https://github.com/amazon-science/spot-diff" target="_blank" rel="noreferrer">Dataset source</a> · <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noreferrer">CC BY 4.0</a>.</p></>;}
function Page({path,data}){if(path.startsWith('/read/')){let file;try{file=decodeURIComponent(path.slice(6));}catch{file='';}return <EvidenceReader file={file} data={data} LinkComponent={Link}/>;}if(path==='/inspect')return <Inspect data={data}/>;if(path==='/journey'||path.startsWith('/journey/'))return <Journey data={data} stageId={path.split('/')[2]}/>;if(path==='/model')return <Model data={data}/>;if(path==='/about')return <About data={data}/>;return <><h1>Page not found.</h1><Link to="/">Return to the workbench</Link></>;}
createRoot(document.getElementById('root')).render(<MotionConfig reducedMotion="user"><App/></MotionConfig>);
