import React,{useEffect,useState} from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import Papa from 'papaparse';
export const rawEvidence=p=>'/evidence/'+p.split('/').map(encodeURIComponent).join('/');
export const readerURL=p=>'/read/'+p.split('/').map(encodeURIComponent).join('/');
const modelFiles=['final_model_receipt.json','final_config.json','final_metrics.json','limitations.md','reproducibility.md','final_bank_hash.txt'].map(p=>'artifacts/model_v1/'+p);
function catalogue(data){const files=new Map(data.evidenceIndex.files.map(s=>[s.path,s]));for(const s of data.journey.stages){for(const x of [...s.sources,...s.metrics.map(m=>m.source)])files.set(x.path,x);}for(const x of data.purpose.sources)files.set(x.path,x);for(const path of modelFiles)if(!files.has(path))files.set(path,{path});return files;}
const names={'README.md':'Project history','requirements.lock':'Python dependencies','final_model_receipt.json':'Model freeze record','final_config.json':'Model configuration','final_metrics.json':'Complete model results','limitations.md':'Model limitations','reproducibility.md':'Reproduce the model','final_bank_hash.txt':'Normal memory identity'};
export function sourceTitle(source){return source.title||names[source.path.split('/').pop()]||source.path.split('/').pop().replace(/\.(md|csv|json|txt)$/,'').replaceAll('_',' ').replace(/^./,c=>c.toUpperCase());}
function Values({value}){if(value===null)return <span>None</span>;if(typeof value!=='object')return <span>{String(value)}</span>;if(Array.isArray(value))return <ol className="record-array">{value.map((v,i)=><li key={i}><Values value={v}/></li>)}</ol>;return <dl className="record-fields">{Object.entries(value).map(([k,v])=><div key={k}><dt>{k.replaceAll('_',' ')}</dt><dd>{typeof v==='object'&&v!==null?<details open><summary>{Array.isArray(v)?v.length+' items':'Details'}</summary><Values value={v}/></details>:<Values value={v}/>}</dd></div>)}</dl>;}
function Grid({rows,caption}){return <div className="document-table" tabIndex="0" role="region" aria-label={caption}><table><caption>{caption}</caption><thead><tr>{rows[0]?.map((v,i)=><th scope="col" key={i}>{v}</th>)}</tr></thead><tbody>{rows.slice(1).map((row,i)=><tr key={i}>{row.map((v,k)=><td key={k}>{v}</td>)}</tr>)}</tbody></table></div>;}
export default function EvidenceReader({file,data,LinkComponent}){
 const files=catalogue(data),source=files.get(file);const [state,setState]=useState({file:'',text:'',error:''});const [attempt,setAttempt]=useState(0);
 const image=/\.(png|jpg|jpeg|webp)$/i.test(file);
 useEffect(()=>{if(!source||image)return;const controller=new AbortController();setState({file,text:'',error:''});fetch(rawEvidence(file),{signal:controller.signal}).then(r=>{if(!r.ok)throw Error('This source could not be loaded.');return r.text();}).then(text=>setState({file,text,error:''})).catch(e=>{if(e.name!=='AbortError')setState({file,text:'',error:e.message});});return()=>controller.abort();},[file,attempt,Boolean(source)]);
 if(!source)return <><h1>Source not available.</h1><p>Choose a source from the methods or journey pages.</p><LinkComponent to="/about#methods" className="text-link">Back to methods</LinkComponent></>;
 const title=sourceTitle(source);const ready=image||(state.file===file&&Boolean(state.text));
 function linked({href='',children}){if(href.startsWith('#'))return <a href={href}>{children}</a>;if(/^(https?:|mailto:)/i.test(href))return <a href={href} target="_blank" rel="noreferrer">{children}</a>;let target;try{target=decodeURIComponent(new URL(href,'https://evidence.local/'+file).pathname.slice(1));}catch{return <span>{children}</span>;}if(files.has(target))return <LinkComponent to={readerURL(target)}>{children}</LinkComponent>;return <a href={'https://github.com/beam-9/pcb-inspection/blob/'+data.model.recipe_commit+'/'+target} target="_blank" rel="noreferrer">{children}</a>;}
 function pictured({src='',alt=''}){let target;try{target=decodeURIComponent(new URL(src,'https://evidence.local/'+file).pathname.slice(1));}catch{return <span>{alt}</span>;}return files.has(target)?<img src={rawEvidence(target)} alt={alt}/>:<span>{alt}</span>;}
 let body;if(ready){if(image)body=<img src={rawEvidence(file)} alt={title}/>;else if(file.endsWith('.md'))body=<ReactMarkdown remarkPlugins={[remarkGfm]} skipHtml components={{a:linked,img:pictured,table:({children})=><div className="document-table" tabIndex="0" role="region" aria-label="Source table"><table>{children}</table></div>}}>{state.text}</ReactMarkdown>;else if(file.endsWith('.csv'))body=<Grid rows={Papa.parse(state.text,{skipEmptyLines:true}).data} caption={title}/>;else if(file.endsWith('.json')){try{body=<Values value={JSON.parse(state.text)}/>;}catch{body=<pre>{state.text}</pre>;}}else if(file==='requirements.lock')body=<Grid rows={[["Package","Pinned version"],...state.text.trim().split('\n').filter(s=>s.includes('==')).map(s=>s.split('=='))]} caption="Python environment dependencies"/>;else body=<pre>{state.text}</pre>;}
 return <><LinkComponent to="/about#methods" className="text-link">Back to tools and methods</LinkComponent><div className="page-heading document-heading"><h1>{title}</h1><p>Original project source</p></div><div className="document-actions"><span>{file}</span><a href={rawEvidence(file)} download={file.split('/').pop()}>Download original file</a></div>{source.sha256&&<details className="source-identity"><summary>File identity (SHA-256)</summary><code>{source.sha256}</code></details>}<article className="document-body" aria-label={title}>{state.error?<div role="alert"><p>{state.error}</p><button className="button" onClick={()=>setAttempt(x=>x+1)}>Try again</button></div>:ready?body:<p role="status">Loading source…</p>}</article></>;
}
